# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mdb-service-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mdb-nexus-permission
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["orgactivewatcher.edge-orchestrator.intel.com"]
    resources: ["orgactivewatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["projectactivewatcher.edge-orchestrator.intel.com"]
    resources: ["projectactivewatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["orgwatcher.edge-orchestrator.intel.com"]
    resources: ["orgwatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["projectwatcher.edge-orchestrator.intel.com"]
    resources: ["projectwatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tenancy.edge-orchestrator.intel.com"]
    resources: ["multitenancies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtime.edge-orchestrator.intel.com"]
    resources: ["runtimes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimeorg.edge-orchestrator.intel.com"]
    resources: ["runtimeorgs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimefolder.edge-orchestrator.intel.com"]
    resources: ["runtimefolders"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimeproject.edge-orchestrator.intel.com"]
    resources: ["runtimeprojects"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "license.edge-orchestrator.intel.com" ]
    resources: [ "licenses" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mdb-nexus-permission
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: mdb-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: mdb-nexus-permission
  apiGroup: rbac.authorization.k8s.io
