# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    cooldown:
      default-days: 7
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:  # Internal dependencies are update into separate PRs.
          - "*open-edge-platform*"
      internal-dependencies:
        patterns:
          - "*open-edge-platform*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[gha] "
    cooldown:
      default-days: 7
