encoders:
  json:
    fields:
      - message
      - level:
          format: uppercase
      - caller:
          format: short
      - timestamp:
          format: iso8601

writers:
  stdout:
    encoder: json

rootLogger:
  level: debug
  outputs:
    - stdout