/*
* SPDX-FileCopyrightText: (C) 2023 Intel Corporation
* SPDX-License-Identifier: Apache-2.0
*/

// Package restClient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.0 DO NOT EDIT.
package restClient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// MetadataServiceDelete request
	MetadataServiceDelete(ctx context.Context, params *MetadataServiceDeleteParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MetadataServiceGetMetadata request
	MetadataServiceGetMetadata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MetadataServiceCreateOrUpdateMetadata request with any body
	MetadataServiceCreateOrUpdateMetadataWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	MetadataServiceCreateOrUpdateMetadata(ctx context.Context, body MetadataServiceCreateOrUpdateMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MetadataServiceDeleteProject request
	MetadataServiceDeleteProject(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) MetadataServiceDelete(ctx context.Context, params *MetadataServiceDeleteParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetadataServiceDeleteRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MetadataServiceGetMetadata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetadataServiceGetMetadataRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MetadataServiceCreateOrUpdateMetadataWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetadataServiceCreateOrUpdateMetadataRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MetadataServiceCreateOrUpdateMetadata(ctx context.Context, body MetadataServiceCreateOrUpdateMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetadataServiceCreateOrUpdateMetadataRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MetadataServiceDeleteProject(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetadataServiceDeleteProjectRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewMetadataServiceDeleteRequest generates requests for MetadataServiceDelete
func NewMetadataServiceDeleteRequest(server string, params *MetadataServiceDeleteParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata.orchestrator.apis/v1/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	queryValues := queryURL.Query()

	if params.Key != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "key", runtime.ParamLocationQuery, *params.Key); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	if params.Value != nil {

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "value", runtime.ParamLocationQuery, *params.Value); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

	}

	queryURL.RawQuery = queryValues.Encode()

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMetadataServiceGetMetadataRequest generates requests for MetadataServiceGetMetadata
func NewMetadataServiceGetMetadataRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata.orchestrator.apis/v1/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMetadataServiceCreateOrUpdateMetadataRequest calls the generic MetadataServiceCreateOrUpdateMetadata builder with application/json body
func NewMetadataServiceCreateOrUpdateMetadataRequest(server string, body MetadataServiceCreateOrUpdateMetadataJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMetadataServiceCreateOrUpdateMetadataRequestWithBody(server, "application/json", bodyReader)
}

// NewMetadataServiceCreateOrUpdateMetadataRequestWithBody generates requests for MetadataServiceCreateOrUpdateMetadata with any type of body
func NewMetadataServiceCreateOrUpdateMetadataRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata.orchestrator.apis/v1/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMetadataServiceDeleteProjectRequest generates requests for MetadataServiceDeleteProject
func NewMetadataServiceDeleteProjectRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metadata.orchestrator.apis/v1/project/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// MetadataServiceDelete request
	MetadataServiceDeleteWithResponse(ctx context.Context, params *MetadataServiceDeleteParams, reqEditors ...RequestEditorFn) (*MetadataServiceDeleteResponse, error)

	// MetadataServiceGetMetadata request
	MetadataServiceGetMetadataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*MetadataServiceGetMetadataResponse, error)

	// MetadataServiceCreateOrUpdateMetadata request with any body
	MetadataServiceCreateOrUpdateMetadataWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MetadataServiceCreateOrUpdateMetadataResponse, error)

	MetadataServiceCreateOrUpdateMetadataWithResponse(ctx context.Context, body MetadataServiceCreateOrUpdateMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*MetadataServiceCreateOrUpdateMetadataResponse, error)

	// MetadataServiceDeleteProject request
	MetadataServiceDeleteProjectWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*MetadataServiceDeleteProjectResponse, error)
}

type MetadataServiceDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MetadataResponse
}

// Status returns HTTPResponse.Status
func (r MetadataServiceDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MetadataServiceDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type MetadataServiceGetMetadataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MetadataResponse
}

// Status returns HTTPResponse.Status
func (r MetadataServiceGetMetadataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MetadataServiceGetMetadataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type MetadataServiceCreateOrUpdateMetadataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MetadataResponse
}

// Status returns HTTPResponse.Status
func (r MetadataServiceCreateOrUpdateMetadataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MetadataServiceCreateOrUpdateMetadataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type MetadataServiceDeleteProjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r MetadataServiceDeleteProjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MetadataServiceDeleteProjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// MetadataServiceDeleteWithResponse request returning *MetadataServiceDeleteResponse
func (c *ClientWithResponses) MetadataServiceDeleteWithResponse(ctx context.Context, params *MetadataServiceDeleteParams, reqEditors ...RequestEditorFn) (*MetadataServiceDeleteResponse, error) {
	rsp, err := c.MetadataServiceDelete(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetadataServiceDeleteResponse(rsp)
}

// MetadataServiceGetMetadataWithResponse request returning *MetadataServiceGetMetadataResponse
func (c *ClientWithResponses) MetadataServiceGetMetadataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*MetadataServiceGetMetadataResponse, error) {
	rsp, err := c.MetadataServiceGetMetadata(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetadataServiceGetMetadataResponse(rsp)
}

// MetadataServiceCreateOrUpdateMetadataWithBodyWithResponse request with arbitrary body returning *MetadataServiceCreateOrUpdateMetadataResponse
func (c *ClientWithResponses) MetadataServiceCreateOrUpdateMetadataWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MetadataServiceCreateOrUpdateMetadataResponse, error) {
	rsp, err := c.MetadataServiceCreateOrUpdateMetadataWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetadataServiceCreateOrUpdateMetadataResponse(rsp)
}

func (c *ClientWithResponses) MetadataServiceCreateOrUpdateMetadataWithResponse(ctx context.Context, body MetadataServiceCreateOrUpdateMetadataJSONRequestBody, reqEditors ...RequestEditorFn) (*MetadataServiceCreateOrUpdateMetadataResponse, error) {
	rsp, err := c.MetadataServiceCreateOrUpdateMetadata(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetadataServiceCreateOrUpdateMetadataResponse(rsp)
}

// MetadataServiceDeleteProjectWithResponse request returning *MetadataServiceDeleteProjectResponse
func (c *ClientWithResponses) MetadataServiceDeleteProjectWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*MetadataServiceDeleteProjectResponse, error) {
	rsp, err := c.MetadataServiceDeleteProject(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetadataServiceDeleteProjectResponse(rsp)
}

// ParseMetadataServiceDeleteResponse parses an HTTP response from a MetadataServiceDeleteWithResponse call
func ParseMetadataServiceDeleteResponse(rsp *http.Response) (*MetadataServiceDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MetadataServiceDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMetadataServiceGetMetadataResponse parses an HTTP response from a MetadataServiceGetMetadataWithResponse call
func ParseMetadataServiceGetMetadataResponse(rsp *http.Response) (*MetadataServiceGetMetadataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MetadataServiceGetMetadataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMetadataServiceCreateOrUpdateMetadataResponse parses an HTTP response from a MetadataServiceCreateOrUpdateMetadataWithResponse call
func ParseMetadataServiceCreateOrUpdateMetadataResponse(rsp *http.Response) (*MetadataServiceCreateOrUpdateMetadataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MetadataServiceCreateOrUpdateMetadataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMetadataServiceDeleteProjectResponse parses an HTTP response from a MetadataServiceDeleteProjectWithResponse call
func ParseMetadataServiceDeleteProjectResponse(rsp *http.Response) (*MetadataServiceDeleteProjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MetadataServiceDeleteProjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
