# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge CI Pipeline

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@0.1.10
    with:
      bootstrap_tools: "go,gotools,golang-lint,helm,yq,buf,opa"
      run_version_check: true
      run_dep_version_check: false
      run_build: true
      run_docker_build: true
      run_docker_push: true
      run_helm_build: true
      run_helm_push: true
      run_version_tag: true
      run_artifact: false
    secrets: inherit
